# A21 assignment
# TODO: comment better
# TODO obviously this isnt a real script, actual implementation will be needed

image: registry.git.chalmers.se/courses/dit638/students/2025-group-04/docker:24.0.5

include:
  - local: '.gitlab-plots.yml'

# Details about how to connect to the Docker service to run this build.
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_CLI_EXPERIMENTAL: enabled

services:
  - name: registry.git.chalmers.se/courses/dit638/students/2025-group-04/docker:24.0.5-dind
    alias: docker

performance_analysis:
  stage: performance-test
  script:
    - pip install requirements.py.dev.txt && ./python/requirements.txt
    - chmod +x run_and_compare.sh
    - ./run_and_compare.sh
  artifacts:
    paths:
      - res/steering_data/comparison_plots
  only:
    - branches
